apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-gen-serviceaccount
  namespace: certs
 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-gen-clusterrole
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
    verbs:
      - get
      - create
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-gen-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-gen-clusterrole
subjects:
  - kind: ServiceAccount
    name: cert-gen-serviceaccount
    namespace: certs